version: 0.2

phases:
  install:
      runtime-versions:
        python: 3.8
      commands: 
        - echo "Installing dependencies..."
        - pip install -r requirements.txt

        
  pre_build:
    commands:
      - echo "Determining changed files..."
      - |
        git fetch --all
        CHANGED_FILES=$(git diff --name-only origin/main $CODEBUILD_WEBHOOK_HEAD_REF)
        echo "CHANGED_FILES: $CHANGED_FILES"
        # Filter for pytest files that start with test_
        PYTEST_FILES=$(echo "$CHANGED_FILES" | grep '^tests/')
        PYLINT_FILES=$(echo "$CHANGED_FILES" | tr ' ' '\n' | grep -E '\.py$)
        if [ -n "$PYTEST_FILES" ]; then
          echo "Test files to be run:"
          echo "$PYTEST_FILES"
          echo "$PYTEST_FILES" > changed_tests.txt
        else
          echo "No test files changed."
          echo "No tests to run."
          touch changed_tests.txt
        fi

        if [ -n "$PYLINT_FILES" ]; then
          echo "Test files to be run:"
          echo "$PYLINT_FILES"
          echo "$PYLINT_FILES" > changed_pylint_files.txt
        else
          echo "No test files changed."
          echo "No tests to run."
          touch changed_pylint_files.txt
        fi

  build:
    commands:
      - echo "Starting Pytest..."
      - |
        # Construct the pytest command with all changed test files
        if [ -s changed_tests.txt ]; then
          PYTEST_COMMAND=$(cat changed_tests.txt | xargs echo python -m pytest)
          echo "Running: $PYTEST_COMMAND"
          $PYTEST_COMMAND
        else
          echo "No test files to run."
        fi

        if [ -s changed_pylint_files.txt ]; then
          PYLINT_COMMAND=$(cat changed_pylint_files.txt | xargs echo pylint --rcfile=.pylintrc)
          echo "Running: $PYLINT_COMMAND"
          $PYLINT_COMMAND
        else
          echo "No test files to run."
        fi
