version: 0.2

phases:
  install:
      runtime-versions:
        python: 3.8
        java: corretto11
      commands:
        - echo "Installing Allure..."
        - |
          curl -o allure-commandline.zip -L "https://dl.bintray.com/qameta/generic/allure-commandline/2.29.0/allure-commandline-2.29.0.zip"
          unzip allure-commandline.zip -d /opt/allure
          export PATH=$PATH:/opt/allure/allure-2.17.0/bin
        
        - echo "Installing dependencies..."
        - pip install -r requirements.txt

        
  pre_build:
    commands:
      - echo "Determining changed files..."
      - |
        # Fetch changes between main and the source branch
        git fetch --all
        CHANGED_FILES=$(git diff --name-only origin/main $CODEBUILD_WEBHOOK_HEAD_REF)
        echo "CHANGED_FILES: $CHANGED_FILES"
        # Filter for pytest files that start with test_
        TEST_FILES=$(echo "$CHANGED_FILES" | awk -F'/' '{print $NF}' | grep '^test_.*\.py$')
        echo "TEST_FILES: $TEST_FILES"
        # If there are test files, set them for pytest
        if [ -n "$TEST_FILES" ]; then
          echo "Test files to be run:"
          echo "$TEST_FILES"
          echo "$TEST_FILES" > changed_tests.txt
        else
          echo "No test files changed."
          echo "No tests to run."
          touch changed_tests.txt
        fi

  build:
    commands:
      - echo "Starting Pytest..."
      - |
        # Construct the pytest command with all changed test files
        if [ -s changed_tests.txt ]; then
          PYTEST_COMMAND=$(cat changed_tests.txt | xargs echo python -m pytest)
          echo "Running: $PYTEST_COMMAND"
          $PYTEST_COMMAND
        else
          echo "No test files to run."
        fi
      - 
