version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8  # Specify the Python version
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt  # Install dependencies from requirements.txt
