version: 0.2

phases:
  pre_build:
    commands:
      - echo "Determining changed files..."
      - |
        # Fetch changes between main and the source branch
        echo "Source branch name: $GITHUB_REPO_NAME"
        echo "Source branch name: $CODEBUILD_RESOLVED_SOURCE_VERSION"

