version: 0.2

phases:
  pre_build:
    commands:
      - echo "Determining changed files..."
      - |
        # Fetch changes between main and the source branch
        git fetch --all
        git branch -r
        echo "Source branch name: $CODEBUILD_SOURCE_VERSION"
        git diff --name-only origin/main origin/$CODEBUILD_SOURCE_VERSION
