version: 0.2

phases:
  install:
      runtime-versions:
        python: 3.8
        java: corretto11
      commands:
        - echo "Installing Allure..."
        - |
          wget -q -nv https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          mkdir -p /opt/allure
          tar -zxf allure-2.27.0.tgz -C /opt/allure
          export PATH=$PATH:/opt/allure/allure-2.27.0/bin
        
        - echo "Installing dependencies..."
        - pip install -r requirements.txt
        - allure --version
        
  pre_build:
    commands:
      - echo "Determining changed files..."
      - |
        git fetch --all
        CHANGED_FILES=$(git diff --name-only origin/main $CODEBUILD_WEBHOOK_HEAD_REF)
        echo "CHANGED_FILES: $CHANGED_FILES"
        TEST_FILES=$(echo "$CHANGED_FILES" | grep '^tests/')
        echo "TEST_FILES: $TEST_FILES"
        if [ -n "$TEST_FILES" ]; then
          echo "Test files to be run:"
          echo "$TEST_FILES"
          echo "$TEST_FILES" > changed_tests.txt
        else
          echo "No test files changed."
          echo "No tests to run."
          touch changed_tests.txt
        fi
        
  build:
    commands:
      - echo "validate allure command"
      - allure --version
      - echo "Starting Pytest..."
      - |
        # Construct the pytest command with all changed test files
        if [ -s changed_tests.txt ]; then
          PYTEST_COMMAND="python -m pytest $(cat changed_tests.txt) --alluredir=RunTestFile"
          echo "Running: $PYTEST_COMMAND"
          $PYTEST_COMMAND
        else
          echo "No test files to run."
        fi
      - allure generate --single-file --clean RunTestFile -o RunTestFileReportResults 
      - zip -r RunTestFileReportResults.zip RunTestFileReportResults

  artifacts:
    files:
      - RunTestFileReportResults.zip
    discard-paths: yes

      
