version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo "Setting status to pending"
      - curl -H "Authorization: token $GITHUB_TOKEN" -d '{"state": "pending", "context": "ci/codebuild", "description": "Build started"}' "https://api.github.com/repos/your-repo-owner/your-repo-name/statuses/$CODEBUILD_RESOLVED_SOURCE_VERSION"
  build:
    commands:
      - echo "Starting build..."
      - echo "Buld Done"
  post_build:
    commands:
      - |
        if [ $? -eq 0 ]; then
          STATUS="success"
          DESCRIPTION="Build succeeded"
        else
          STATUS="failure"
          DESCRIPTION="Build failed"
        fi
      - curl -H "Authorization: token $GITHUB_TOKEN" -d '{"state": "'"$STATUS"'", "context": "ci/codebuild", "description": "'"$DESCRIPTION"'"}' "https://api.github.com/repos/your-repo-owner/your-repo-name/statuses/$CODEBUILD_RESOLVED_SOURCE_VERSION"
