version: 0.2

phases:      
  build:
    commands:
      - mkdir -p TestExamples 
      - zip -r TestExamples.zip TestExamples

artifacts:
  files: TestExamples.zip
  name: test_directory
  discard-paths: yes

      
