version: 0.2

env:
  variables:
    pytest_defult_command: python -m pytest
    pytest_defulat_dir: ReportResults

phases:
  pre_build:
    commands:
      - echo "Pre-build phase"
      - echo "ENV_VAR1 is $ENV_VAR1"
      - echo "ENV_VAR2 is $ENV_VAR2"
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Using environment variables"
      - echo "ENV_VAR1 $ENV_VAR1"
      - echo "ENV_VAR2 $ENV_VAR2"
