version: 0.2

phases:
  pre_build:
    commands:
      - echo "Determining changed files..."
      - |
        # Fetch changes between main and the source branch
        git fetch origin
        SOURCE_BRANCH_NAME=$CODEBUILD_SOURCE_VERSION
        CHANGED_FILES=$(git diff --name-only origin/main origin/$SOURCE_BRANCH_NAME)
        
        # Filter for pytest files that start with test_
        TEST_FILES=$(echo "$CHANGED_FILES" | grep -E '^test_.*\.py$')
        echo "$TEST_FILES"
