version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo "Setting status to pending"
      - |
        # Construct the build URL
        BUILD_URL="https://console.aws.amazon.com/codesuite/782727060089/projects/$CODEBUILD_BUILD_PROJECT_NAME/build/$CODEBUILD_BUILD_ID/view"
        curl -H "Authorization: token $GITHUB_TOKEN" \
        -d '{"state": "pending", "context": "ci/codebuild", "description": "Build started", "target_url": "'"$BUILD_URL"'"}' \
        "https://api.github.com/repos/$GITHUB_REPO_OWNER/$GITHUB_REPO_NAME/statuses/$CODEBUILD_RESOLVED_SOURCE_VERSION"
  build:
    commands:
      - echo "Starting build..."
      - echo "Build Done"
  post_build:
    commands:
      - |
        # Construct the build URL
        BUILD_URL="https://console.aws.amazon.com/codesuite/782727060089/projects/$CODEBUILD_BUILD_PROJECT_NAME/build/$CODEBUILD_BUILD_ID/view"
        if [ $? -eq 0 ]; then
          STATUS="success"
          DESCRIPTION="Build succeeded"
        else
          STATUS="failure"
          DESCRIPTION="Build failed"
        fi
        curl -H "Authorization: token $GITHUB_TOKEN" \
        -d '{"state": "'"$STATUS"'", "context": "ci/codebuild", "description": "'"$DESCRIPTION"'", "target_url": "'"$BUILD_URL"'"}' \
        "https://api.github.com/repos/$GITHUB_REPO_OWNER/$GITHUB_REPO_NAME/statuses/$CODEBUILD_RESOLVED_SOURCE_VERSION"
